baseurl: /
languageCode: en-us
title: Experiments
theme: hugo-ivy
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
summaryLength: 100

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 10
    - name: "The Garden"
      url: "/categories/Garden/"
    - name: "Poetry"
      url: "/categories/Poetry/"
      weight: 15
    - name: "About"
      url: "/about/"
      weight: 30
    - name: "Tags"
      url: "/tags/"
      weight: 50
    - name: "Subscribe"
      url: "/index.xml"

params:
  description: "Reports from experiments of Pragun Goyal"
  footer: "&copy; [Pragun Goyal](https://pragun.github.io) 2017-{Year} | [Github](https://github.com/pragun)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
